[package]
name = "ttv"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
color-eyre = "0.6.4"
crossterm = "0.29.0"
ffmpeg = { version = "7.1.0", package = "ffmpeg-next" }
image = "0.25.6"
ratatui = "0.29.0"
ratatui-image = "8.0.0"
